package com.charles.schwab.agentic.orchestrator.graph;

public enum NodeId {
    ANALYZE_REQUIREMENTS,
    HUMAN_AMBIGUITY_INPUT,
    BROWNFIELD_IMPACT_ANALYSIS,
    DESIGN_ARCHITECTURE,
    HUMAN_APPROVAL_GATE,
    WRITE_BACKEND_CODE,
    WRITE_FRONTEND_CODE,
    SECURITY_COMPLIANCE_AUDIT,
    RUN_QA,
    ROLLBACK,
    RE_PLAN_TASKS,
    SAFE_STOP,
    SYNTHESIZE_SUMMARY,
    END
}
